### ISSUE TITLE
Overview of programming season

### ISSUE THREAD

**Issue by pi-this** [535tobor/2023-2024SeasonCode#1]
Greetings, and welcome to this year's FTC game season, Center Stage. It is always advisable to organize your code and add various commenting techniques. This year, Tobor has introduced an operations folder that contains all the operations for the entire season. Outside the operations folder are the Autonomous and TeleOp project files, which are Java projects that can be selected within the driver station. Any files within the team code and outside the operations folder can be run as TeleOp or Autonomous from the driver station. Team Tobor is excited to experiment with this new coding technique of operational organization. We are thrilled to undertake adventures into editing, experimenting, and exploring new ways to improve the code for this year's season, Center Stage. So, with that said, Tobor hopes all the FTC teams around the world will have a wonderful experience and says, “You are going to do great!”

A new form of organization that I like to call operational organization was added to the team code: 
https://github.com/535tobor/2023-2024SeasonCode/tree/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/operations

Tobor's tensor flow model has been added to the code for use in Autonomous:
https://github.com/535tobor/2023-2024SeasonCode/tree/master/FtcRobotController/src/main/assets

Various Enums have been added to the code for organization:
<pre>
package org.firstinspires.ftc.teamcode.operations;

public enum Wheels {
    FRONT_LEFT("fl"),
    FRONT_RIGHT("fr"),
    BACK_LEFT("bl"),
    BACK_RIGHT("br");

    private final String name;

    Wheels(final String name) {this.name = name;}

    public String abbreviation() {
        return name;
    }
}
</pre>

An interface was added to the operational organization of the code for higher performance:
<pre>
// public is not needed, because Interface has public by default
package org.firstinspires.ftc.teamcode.operations;

 interface TargetSetup {
     /*
     this interface was made so that
     both LinearOpMode and OpMode can be
     ran within the same class
      */
     void runInit();
     void runInitLoop();
     void runStart();
     void runLoop();
     void runStop();
}
</pre>

In Operational Organization the code has a target operations file. In this setup, any file that is called 'Target' at the beginning of the name means that the file is the head class of that folder. For example, the head class of the folder operations is the 
'TargetOperations' file, shown below:
<pre>
package org.firstinspires.ftc.teamcode.operations;

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

public abstract class TargetOperations extends LinearOpMode implements TargetSetup {

    public static boolean pixelMotorConfig = false;
    public static boolean barMotorConfig = false;

    public void stopAll() {
        requestOpModeStop();
    }

}
</pre>

By using 'TargetOperations' as the head operations class, I can extend the class in my TeleOp project like so:
<pre>
public class GameCode extends TargetOperations
</pre>

**Comment by 535tobor** [comment]
Check out the Tobor Programming website for Center Stage at [https://535tobor.github.io/CenterStage](https://535tobor.github.io/CenterStage). This website includes information about the programming for this season.
